///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("affcee34-1eb0-4ead-ba6a-4b1d17023432")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("affcee34-1eb0-4ead-ba6a-4b1d17023432")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "affcee34-1eb0-4ead-ba6a-4b1d17023432", ".\\RepositoryImages\\MyTest1Repositoryaffcee34.rximgres")
        {
            _calculator = new MyTest1RepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("affcee34-1eb0-4ead-ba6a-4b1d17023432")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("6662c7d8-75ca-4966-a8ae-aa885f1f18ec")]
        public virtual MyTest1RepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("6662c7d8-75ca-4966-a8ae-aa885f1f18ec")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num2buttonInfo;
            RepoItemInfo _plusbuttonInfo;
            RepoItemInfo _num5buttonInfo;
            RepoItemInfo _equalbuttonInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "6662c7d8-75ca-4966-a8ae-aa885f1f18ec", "")
            {
                _num2buttonInfo = new RepoItemInfo(this, "Num2Button", ".//container[@automationid='NumberPad']/button[@automationid='num2Button']", ".//button[@automationid='num2Button']", 30000, null, "83156fe8-1e18-4f06-8021-a612da2813cf");
                _plusbuttonInfo = new RepoItemInfo(this, "PlusButton", ".//container[@automationid='StandardOperators']/button[@automationid='plusButton']", ".//button[@automationid='plusButton']", 30000, null, "a8431cca-e48e-4022-92a2-c03ed526a0a6");
                _num5buttonInfo = new RepoItemInfo(this, "Num5Button", ".//container[@automationid='NumberPad']/button[@automationid='num5Button']", ".//button[@automationid='num5Button']", 30000, null, "d17a324c-b0a5-4efc-b930-5892fd922a0d");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", ".//container[@automationid='StandardOperators']/button[@automationid='equalButton']", ".//button[@automationid='equalButton']", 30000, null, "0d053a47-d43b-4f02-9cd8-b5ca11377cb3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6662c7d8-75ca-4966-a8ae-aa885f1f18ec")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6662c7d8-75ca-4966-a8ae-aa885f1f18ec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num2Button item.
            /// </summary>
            [RepositoryItem("83156fe8-1e18-4f06-8021-a612da2813cf")]
            public virtual Ranorex.Button Num2Button
            {
                get
                {
                    return _num2buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num2Button item info.
            /// </summary>
            [RepositoryItemInfo("83156fe8-1e18-4f06-8021-a612da2813cf")]
            public virtual RepoItemInfo Num2ButtonInfo
            {
                get
                {
                    return _num2buttonInfo;
                }
            }

            /// <summary>
            /// The PlusButton item.
            /// </summary>
            [RepositoryItem("a8431cca-e48e-4022-92a2-c03ed526a0a6")]
            public virtual Ranorex.Button PlusButton
            {
                get
                {
                    return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusButton item info.
            /// </summary>
            [RepositoryItemInfo("a8431cca-e48e-4022-92a2-c03ed526a0a6")]
            public virtual RepoItemInfo PlusButtonInfo
            {
                get
                {
                    return _plusbuttonInfo;
                }
            }

            /// <summary>
            /// The Num5Button item.
            /// </summary>
            [RepositoryItem("d17a324c-b0a5-4efc-b930-5892fd922a0d")]
            public virtual Ranorex.Button Num5Button
            {
                get
                {
                    return _num5buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num5Button item info.
            /// </summary>
            [RepositoryItemInfo("d17a324c-b0a5-4efc-b930-5892fd922a0d")]
            public virtual RepoItemInfo Num5ButtonInfo
            {
                get
                {
                    return _num5buttonInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("0d053a47-d43b-4f02-9cd8-b5ca11377cb3")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("0d053a47-d43b-4f02-9cd8-b5ca11377cb3")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
